-- Tabel Users (Ekstensi dari Auth Users)
CREATE TABLE public.users (
    id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
    email TEXT NOT NULL,
    role TEXT DEFAULT 'siswa' CHECK (role IN ('admin', 'siswa')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabel Questions
CREATE TABLE public.questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    soal TEXT NOT NULL,
    pilihan_a TEXT NOT NULL,
    pilihan_b TEXT NOT NULL,
    pilihan_c TEXT NOT NULL,
    pilihan_d TEXT NOT NULL,
    jawaban_benar TEXT NOT NULL CHECK (jawaban_benar IN ('A', 'B', 'C', 'D')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabel Answers
CREATE TABLE public.answers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    question_id BIGINT REFERENCES public.questions NOT NULL,
    jawaban TEXT NOT NULL CHECK (jawaban IN ('A', 'B', 'C', 'D')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabel Results
CREATE TABLE public.results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users NOT NULL,
    nilai NUMERIC NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.answers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.results ENABLE ROW LEVEL SECURITY;

-- Helper function to check if user is admin (SECURITY DEFINER to avoid recursion)
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.users
    WHERE id = auth.uid() AND role = 'admin'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Policies for Users
CREATE POLICY "Users can view their own data" ON public.users FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Admins can view all users" ON public.users FOR SELECT USING (public.is_admin());

-- Policies for Questions
CREATE POLICY "Everyone can view questions" ON public.questions FOR SELECT USING (true);
CREATE POLICY "Admins can manage questions" ON public.questions FOR ALL USING (public.is_admin());

-- Policies for Answers
CREATE POLICY "Users can manage their own answers" ON public.answers FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "Admins can view all answers" ON public.answers FOR SELECT USING (public.is_admin());

-- Policies for Results
CREATE POLICY "Users can view their own results" ON public.results FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own results" ON public.results FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Admins can view all results" ON public.results FOR SELECT USING (public.is_admin());

-- Function to handle new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.users (id, email, role)
    VALUES (
        NEW.id,
        NEW.email,
        CASE
            WHEN (SELECT COUNT(*) FROM public.users) = 0 THEN 'admin'
            ELSE 'siswa'
        END
    );
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger for new user signup
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Contoh Soal TKJ
INSERT INTO public.questions (soal, pilihan_a, pilihan_b, pilihan_c, pilihan_d, jawaban_benar) VALUES
('Apa kepanjangan dari IP Address?', 'Internet Protocol Address', 'Internal Protocol Address', 'Internet Package Address', 'Internal Package Address', 'A'),
('Perangkat yang berfungsi untuk menghubungkan dua jaringan yang berbeda adalah...', 'Hub', 'Switch', 'Router', 'Modem', 'C'),
('Layer OSI yang bertanggung jawab untuk pengiriman data end-to-end adalah...', 'Physical Layer', 'Data Link Layer', 'Network Layer', 'Transport Layer', 'D'),
('Topologi jaringan yang setiap komputernya terhubung ke satu kabel pusat disebut...', 'Topologi Star', 'Topologi Bus', 'Topologi Ring', 'Topologi Mesh', 'B'),
('Protokol yang digunakan untuk mengirim email adalah...', 'HTTP', 'FTP', 'SMTP', 'POP3', 'C');
